version: '3.7'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./public:/var/www/html
  db:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=cyrela
      - MYSQL_ROOT_PASSWORD=123456
